### PR TITLE
Quote the pip install specification in development docs

### PR DESCRIPTION
**Pull request by mfisher87**
Woops! Excellent catch @itcarroll 

----
📚 Documentation preview 📚: https://earthaccess--814.org.readthedocs.build/en/814/

### CODE REVIEW

**Review by chuckwondo — COMMENTED** [review]
The quotes are unnecessary

**Comment by chuckwondo** [comment]
I suggest closing this PR, as the quotes are unnecessary.

**Comment by itcarroll** [comment]
I think they are necessary in macOS zsh.

```
% pip install -e .[tests,doc,dev]
zsh: no matches found: .[tests,doc,dev]
```

**Comment by jhkennedy** [comment]
Yes, `[` and `]` are char-set wildcards in zsh and I can confirm I hit this issue as well. Zsh is the default shell on macs now, so we should be zsh safe in our docs.

**Review by jhkennedy — APPROVED** [review]

**Comment by chuckwondo** [comment]
Sorry, I'm still on bash, so didn't realize this is a problem for zsh.

**Review by chuckwondo — APPROVED** [review]

**Comment by mfisher87** [comment]
:rocket:

**Pull request merged**
