### PR TITLE
Cleanup vestigial GH Actions YAML for documentation

### PR DESCRIPTION
**Pull request by mfisher87**
See #274 for more

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks! I'm curious if we need this workflow at all anymore? Maybe we just stick with readthedocs for all documentation builds?

**Comment by mfisher87** [comment]
Normally I'd say let's put it all in one place, but in this case I'm not sure. We've already shared out links to the earthaccess documentation. @betolink @asteiker thoughts?

**Review by betolink — COMMENTED** [review]
If I'm reading this correctly, we are not deploying the documentation for PRs?

**Comment by mfisher87** [comment]
ReadTheDocs is deploying docs for PRs. If you click "Show all checks" for this PR you can see the successful build. We didn't need PR previews on both RTD _and_ GitHub Pages, so the original intent of this PR was to remove the redundancy.

Now that we've decided that GH Pages will redirect to RTD, we no longer need this PR.

**Pull request closed without merging**
