### PR TITLE
add obdaac s3-credential endpoint

### PR DESCRIPTION
**Pull request by itcarroll**
OB.DAAC is joining the PARTY!

----
📚 Documentation preview 📚: https://earthaccess--516.org.readthedocs.build/en/516/

### CODE REVIEW

**Review by jhkennedy — DISMISSED** [review]
Looks good to me! I confirmed the homepage change and that the s3-redentials endpoint README is there:
https://obdaac-tea.earthdatacloud.nasa.gov/s3credentialsREADME

**Comment by itcarroll** [comment]
Thanks! Waiting to unset `draft` to get a nod from our programmers.

**Comment by quixrick** [comment]
This looks okay to me.  👍  
-Rick

**Comment by itcarroll** [comment]
@jhkennedy Your review (which, while appreciated, came earlier than desired) was abrogated when I unset `draft`. Ready for review now, please & thank you.

**Review by betolink — APPROVED** [review]
Nice! just a note, S3 credentials are also picked up from the metadata if they are available. Eventually these hard-coded values should go away, in real life I don't know how good metadata will be from CMR cc @jhkennedy

**Comment by itcarroll** [comment]
@betolink These hard-coded values would still be needed for `earthaccess.get_s3fs_session(daac="OBDAAC")` though, right? Maybe that would go away too?

**Comment by betolink** [comment]
Yeah they are still needed for that. Only when we use the results to download or open is when we don't really need them if the metadata is right. I guess they won't go away anytime soon.

**Pull request merged**
