### PR TITLE
Drop support for Python 3.9; eliminate duplicate run of test-mindeps CI 

### LINKED ISSUE #836: Drop support for Python 3.9
We are now in Q4 of 2024, and [per SPEC0, it's time to drop support for Python 3.10](https://scientific-python.org/specs/spec-0000/#2024---quarter-4). We still support 3.9, so perhaps we should drop 3.9 in our next release, and 3.10 in the following one.

### PR DESCRIPTION
**Pull request by mfisher87**
Following [SPEC0](https://scientific-python.org/specs/spec-0000/), we can stop supporting Python 3.9. We can also stop supporting 3.10, but we decided to give 3.10 a little more time before dropping. Resolves #836.

<details><summary>Pull Request (PR) draft checklist - click to expand</summary>

- [x] Please review our
      [contributing documentation](https://earthaccess.readthedocs.io/en/latest/contributing/)
      before getting started.
- [x] Populate a descriptive title. For example, instead of "Updated README.md", use a
      title such as "Add testing details to the contributor section of the README".
      Example PRs: [#763](https://github.com/nsidc/earthaccess/pull/763)
- [x] Populate the body of the pull request with:
    - A clear description of the change you are proposing.
    - Links to any issues resolved by this PR with text in the PR description, for
      example `closes #1`. See
      [GitHub docs - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
- [ ] Update `CHANGELOG.md` with details about your change in a section titled
      `## Unreleased`. If such a section does not exist, please create one. Follow
      [Common Changelog](https://common-changelog.org/) for your additions.
      Example PRs: [#763](https://github.com/nsidc/earthaccess/pull/763)
- [x] Update the documentation and/or the `README.md` with details of changes to the
      earthaccess interface, if any. Consider new environment variables, function names,
      decorators, etc.

Click the "Ready for review" button at the bottom of the "Conversation" tab in GitHub
once these requirements are fulfilled. Don't worry if you see any test failures in
GitHub at this point!

</details>

<details><summary>Pull Request (PR) merge checklist - click to expand</summary>

Please do your best to complete these requirements! If you need help with any of these
requirements, you can ping the `@nsidc/earthaccess-support` team in a comment and we
will help you out!

- [x] Add unit tests for any new features.
- [x] Apply formatting and linting autofixes. You can add a GitHub comment in this Pull
      Request containing "pre-commit.ci autofix" to automate this.
- [ ] Ensure all automated PR checks (seen at the bottom of the "conversation" tab) pass.
- [ ] Get at least one approving review.

</details>

----
📚 Documentation preview 📚: https://earthaccess--876.org.readthedocs.build/en/876/

### CODE REVIEW

**Comment by mfisher87** [comment]
```
  Caused by: Failed to download and build `h5py==3.0.0`
  <...>
  Caused by: Failed to download and build `numpy==1.19.3`
```

?? Our minimum supported version of numpy is 1.24.0. Is `uv` failing to understand our conditional numpy dependency?

**Comment by mfisher87** [comment]
Removed the numpy conditional dependency after upgrading h5py to a version that supports Python 3.10. Still getting the same error. When I lock the environment locally with lowest-direct resolution, I get: `Updated numpy v2.0.2 -> v1.26.4`. I don't understand where `numpy==1.19.3` is coming from!

**Comment by mfisher87** [comment]
It looks to me like a bug in `uv`'s lowest-direct resolution algorithm. It's pulling in the lowest version for numpy as an indirect dependency of h5py (https://github.com/h5py/h5py/blob/3.4.0/setup.py#L32) and ignoring our direct specification of the lowest numpy version.

**Comment by jhkennedy** [comment]
@mfisher87 this is dumb, but might just work -- can you try putting numpy at the top of the dependencies list so it's before h5py?

**Comment by mfisher87** [comment]
@jhkennedy great idea, but no change :(

**Comment by jhkennedy** [comment]
OK, rats. I was hoping dumb but easy would work. :rofl: 

@mfisher87 in #872, when I pulled the min-deps test into nox, I changed:
```
uv sync --resolution lowest-direct --extra test
uv pip install --no-deps .
```
to
```
uv pip install --resolution lowest-direct --editable .[test]
```
https://github.com/nsidc/earthaccess/pull/872/files#diff-f7a16a65f061822bcc73b8296f4dc837353d379d8d9cc5307982cb6941442835R38

It sounds like from your comments the `uv sync` step first might actually be necessary, so adding that back into the session might be the way to go.

**Comment by mfisher87** [comment]
The `uv sync` command fails with the exact same error output :(

**Comment by jhkennedy** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by mfisher87** [comment]
I'm thinking open an issue on the `uv` repo for this. What do you think?

**Comment by jhkennedy** [comment]
> I'm thinking open an issue on the uv repo for this. What do you think?

Makes sense -- there's a couple that look like they might be related already open. E.g., 
https://github.com/astral-sh/uv/issues/5492

But I'm in a meeting so haven't ready them closely (I'm all booked today :sob: )

**Comment by mfisher87** [comment]
I never did figure out the underlying cause. `pip install h5py==3.4.0` doesn't work in a Python 3.10 environment either; it attempts to build the wheel, and pulls in the lowest supported version of numpy. I expected it would pull in a version of numpy which supported Python 3.10.

Either way, we can avoid building the wheel by upgrading `h5py >=3.6.0`, which has a pre-built wheel for Python 3.10, and that fixes the error!

**Review by jhkennedy — APPROVED** [review]
The 3.10 and 3.11 integration tests failed because 6 tests failed, while in 3.12 and 3.13 only 5 failed, which is below our threshold. The additional failure is just a flakey failure, so I think were g2g. :shipit:

**Comment by mfisher87** [comment]
:rofl:

**Pull request merged**
