### PR TITLE
Add test text to trigger RTD in PR

### PR DESCRIPTION
**Pull request by MattF-NSIDC**

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Nice! Looks like things are working https://earthaccess--285.org.readthedocs.build/en/285/howto/search-granules/

**Comment by MattF-NSIDC** [comment]
:tada:  There is an error in a tutorial that we don't yet know how to resolve, but we'll get to that at some point :)

```
ValueError: did not find a match in any of xarray's currently installed IO backends ['h5netcdf']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:

https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
```

**Comment by MattF-NSIDC** [comment]
@jrbourbeau can we get your RTD username?

**Comment by jrbourbeau** [comment]
It's `jrbourbeau`

**Comment by MattF-NSIDC** [comment]
Invited, thanks :)

**Pull request closed without merging**
