### PR TITLE
Format and lint notebooks

### LINKED ISSUE #788: Lint and format Jupyter Notebooks
Ruff 0.6.0 is out and lints Jupyter notebooks by default: https://astral.sh/blog/ruff-v0.6.0#jupyter-notebooks-are-now-linted-and-formatted-by-default

To prevent errors on PRs which don't introduce any new lint/formatting issues, we should either lint & format the notebooks or disable for Jupyter notebooks following the info in the link above.

### PR DESCRIPTION
**Pull request by itcarroll**
Closes #788

Re-enable the format and lint tool for notebook (.ipynb) files everywhere in the repo (which turns out to be in `notebooks`, `docs/howto`, and mostly `docs/tutorials`).

The only lint rules I found to be not great for notebooks are [T201](https://docs.astral.sh/ruff/rules/print/) and [T203](https://docs.astral.sh/ruff/rules/p-print/), which are prohibitions on `print` and `pprint` in production code. I ignored them for "*.ipynb" in `[tool.ruff.lint.per-file-ignores]`.

I found two packages missing from `[project.optional-dependencies.docs]` that are needed for the notebooks to run, and added them with ~~a minimum dependency taken from the version pip would install.~~ `uv add --extra docs dask cftime`.

I did not attempt to fix some remaining errors in the notebooks that are beyond the scope of linting. They did not all run when I started and still don't all run (but not because of missing packages!).

<details><summary>Pull Request (PR) draft checklist - click to expand</summary>

- [x] Please review our
      [contributing documentation](https://earthaccess.readthedocs.io/en/latest/contributing/)
      before getting started.
- [x] Ensure an issue exists representing the problem being solved in this PR.
- [x] Populate a descriptive title. For example, instead of "Updated README.md", use a
      title such as "Add testing details to the contributor section of the README".
- [x] Populate the body of the pull request with:
    - A clear description of the change you are proposing.
    - Links to any issues resolved by this PR with text in the PR description, for
      example `closes #1`. See
      [GitHub docs - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
- [x] Update `CHANGELOG.md` with details about your change in a section titled
      `## Unreleased`. If such a section does not exist, please create one. Follow
      [Common Changelog](https://common-changelog.org/) for your additions.
- [x] Update the documentation and/or the `README.md` with details of changes to the
      earthaccess interface, if any. Consider new environment variables, function names,
      decorators, etc.

Click the "Ready for review" button at the bottom of the "Conversation" tab in GitHub
once these requirements are fulfilled. Don't worry if you see any test failures in
GitHub at this point!

</details>

<details><summary>Pull Request (PR) merge checklist - click to expand</summary>

Please do your best to complete these requirements! If you need help with any of these
requirements, you can ping the `@nsidc/earthaccess-support` team in a comment and we
will help you out!

- [x] Add unit tests for any new features.
- [x] Apply formatting and linting autofixes. You can add a GitHub comment in this Pull
      Request containing "pre-commit.ci autofix" to automate this.
- [ ] Ensure all automated PR checks (seen at the bottom of the "conversation" tab) pass.
- [ ] Get at least one approving review.

</details>

----
📚 Documentation preview 📚: https://earthaccess--817.org.readthedocs.build/en/817/

### CODE REVIEW

**Comment by itcarroll** [comment]
```
uv-lock..................................................................Failed
- hook id: uv-lock
- exit code: 2
```

@MattF-NSIDC I'm unable to find an explanation for what to do about pre-commit's uv-lock check, which is no doubt failing because I've added packages to `pyproject.toml`. Can you explain how to safely update `uv.lock`?

**Comment by mfisher87** [comment]
Hey @itcarroll for future reference, I don't log in to @MattF-NSIDC often so I don't see the notifications sent there :)

Did the failing check not also update `uv.lock` when it failed? This was the output for me when I added `flask` to the `dependencies` array in `pyproject.toml`:

```bash
$ pre-commit run -a uv-lock
uv-lock..................................................................Failed
- hook id: uv-lock
- files were modified by this hook

warning: `VIRTUAL_ENV=/home/robatt/.cache/pre-commit/repo16nnfz_r/py_env-python3.12` does not match the project environment path `.venv` and will be ignored
Using Python 3.12.5 interpreter at: /home/robatt/.local/share/miniforge3/envs/earthaccess/bin/python3
Resolved 222 packages in 1.12s
Added blinker v1.8.2
Added flask v3.0.3
Added itsdangerous v2.2.0
Added werkzeug v3.0.4

$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pyproject.toml
	modified:   uv.lock
```

**Comment by mfisher87** [comment]
Oh, and thanks so much for taking on this important piece of technical debt!! :bow:

**Comment by itcarroll** [comment]
Understand now that the uv-lock hook is throwing an error, so that's why it's not updating the `uv.lock` file.

The error I could not make any sense of was

```
(earthaccess) $ pre-commit run uv-lock
warning: `VIRTUAL_ENV=/Users/icarroll/.cache/pre-commit/repo48a95whq/py_env-python3` does not match the project environment path `.venv` and will be ignored
error: Failed to build: `earthaccess @ file:///Users/icarroll/tmp/earthaccess`
  Caused by: Failed to deserialize cache entry
  Caused by: wrong msgpack marker FixArray(2)
```

I tried reinstalling *everything*. What eventually made the error go away was [updating](https://github.com/nsidc/earthaccess/pull/817/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9) the `rev` on the `uv-pre-commit` repo to "0.4.12". Is that okay @mfisher87?

**Comment by mfisher87** [comment]
> I tried reinstalling _everything_. What eventually made the error go away was [updating](https://github.com/nsidc/earthaccess/pull/817/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9) the `rev` on the `uv-pre-commit` repo to "0.4.12". Is that okay @mfisher87?

That's great! Thanks so much for tracking down a fix. That's a really weird error message, I don't know what to make of it :laughing:

**Review by chuckwondo — APPROVED** [review]
LGTM

**Comment by itcarroll** [comment]
@precommit.ci autofix

**Review by chuckwondo — APPROVED** [review]

**Pull request merged**
