### PR TITLE
start work on results classes 

### PR DESCRIPTION
**Pull request by ebolch**
This is what @jhkennedy, @JessicaS11 and I started work on during the 2024-10-29 Hackday. 

The end goal is to return a results class object rather than a list, using the existing `DataCollections` / `DataGranules` classes. This could enable results to be combined (and possibly filtered to only certain assets?)

The first step we discussed/started was adding a `load` method to store actual results and a `granules` property to allow the object to still function as a list.

The long-term plan would have functions like `download` and `open` act on this object rather than expecting the user to supply granules and provider inputs.

There is more discussion [here](https://github.com/nsidc/earthaccess/discussions/847).

<details><summary>Pull Request (PR) draft checklist - click to expand</summary>

- [ ] Please review our
      [contributing documentation](https://earthaccess.readthedocs.io/en/latest/contributing/)
      before getting started.
- [ ] Populate a descriptive title. For example, instead of "Updated README.md", use a
      title such as "Add testing details to the contributor section of the README".
      Example PRs: [#763](https://github.com/nsidc/earthaccess/pull/763)
- [ ] Populate the body of the pull request with:
    - A clear description of the change you are proposing.
    - Links to any issues resolved by this PR with text in the PR description, for
      example `closes #1`. See
      [GitHub docs - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
- [ ] Update `CHANGELOG.md` with details about your change in a section titled
      `## Unreleased`. If such a section does not exist, please create one. Follow
      [Common Changelog](https://common-changelog.org/) for your additions.
      Example PRs: [#763](https://github.com/nsidc/earthaccess/pull/763)
- [ ] Update the documentation and/or the `README.md` with details of changes to the
      earthaccess interface, if any. Consider new environment variables, function names,
      decorators, etc.

Click the "Ready for review" button at the bottom of the "Conversation" tab in GitHub
once these requirements are fulfilled. Don't worry if you see any test failures in
GitHub at this point!

</details>

<details><summary>Pull Request (PR) merge checklist - click to expand</summary>

Please do your best to complete these requirements! If you need help with any of these
requirements, you can ping the `@nsidc/earthaccess-support` team in a comment and we
will help you out!

- [ ] Add unit tests for any new features.
- [ ] Apply formatting and linting autofixes. You can add a GitHub comment in this Pull
      Request containing "pre-commit.ci autofix" to automate this.
- [ ] Ensure all automated PR checks (seen at the bottom of the "conversation" tab) pass.
- [ ] Get at least one approving review.

</details>

----
📚 Documentation preview 📚: https://earthaccess--860.org.readthedocs.build/en/860/

### CODE REVIEW

**Comment by jhkennedy** [comment]
@ebolch great! Thanks for opening the PR! 

How would you live to move forward with it? I can spend a little time hacking and leave some TODOs to circle back to, just outline a gameplan, or we can wait until the next hackday to team up on it? I'm happy to drive or let you drive.

**Comment by ebolch** [comment]
@jhkennedy I'm pretty flexible on how we move forward. I'm planning to spend some time working on this next week, but some guidance on how to make the changes would be great. Feel free to do some hacking or outline TODOs if you have time, otherwise I'll try to make some progress and then we can continue next hackday.

**Comment by JessicaS11** [comment]
@ebolch @jhkennedy Likewise I'd be happy to spend some time contributing to this (and could do so this week), so if it's helpful to assign me a few to-dos, please do!

**Comment by jhkennedy** [comment]
I'm going to close this PR, push this branch directly to nsidc/earthaccess, and open a new PR so that we can collaborate on this feature more easily.

**Pull request closed without merging**
