### PR TITLE
adding doc contribution guidelines

### PR DESCRIPTION
**Pull request by rupesh2**
Thanks to @mfisher87  for the demo and edits!

----
📚 Documentation preview 📚: https://earthaccess--469.org.readthedocs.build/en/469/

### CODE REVIEW

**Comment by mfisher87** [comment]
Thanks so much @rupesh2 ! Just FYI, I no longer use the @MattF-NSIDC account. Keeping track of two accounts was getting to be too much of a headache :)

I may not get to this today, but someone else might!

**Comment by rupesh2** [comment]
sorry, I didn't notice I used your old handle! updated now

**Comment by mfisher87** [comment]
Hey @rupesh2, I intended to get to this by now! Thanks for your patience. One of my dogs needed emergency surgery, and he's fine now, but I'm at least a couple days behind on everything :sweat_smile:

**Comment by rupesh2** [comment]
No worries, @mfisher87 ! I am so sorry to hear - I hope he is recovering well!

**Comment by mfisher87** [comment]
That's my fault, apologies :grimacing:

**Review by mfisher87 — APPROVED** [review]

**Comment by rupesh2** [comment]
Hi @chuckwondo - sorry I missed your post. @mfisher87 Thank you for cleaning up and merging!

**Comment by mfisher87** [comment]
Any time! Thanks for your contribution :)

**Pull request merged**
