### PR TITLE
add ASDC daac entry and cloud provider

### LINKED ISSUE #517: Add ASDC as DAAC and cloud provider
Similar to https://github.com/nsidc/earthaccess/pull/516

### PR DESCRIPTION
**Pull request by danielfromearth**
Closes #517 

----
📚 Documentation preview 📚: https://earthaccess--518.org.readthedocs.build/en/518/

### CODE REVIEW

**Comment by danielfromearth** [comment]
Thanks @ckhowardASDC for your help with the URLs.  I think this is ready for review now.

**Review by mfisher87 — DISMISSED** [review]

**Comment by danielfromearth** [comment]
@mfisher87, the ReadTheDocs is failing — but I'm not sure why.  And I can't find a way to just re-run that mkdocs build step without pushing a new commit. Do you know if that's possible?

**Review by mfisher87 — APPROVED** [review]
LGTM!

EDIT: Reviewed the code before checking the comment. :eyes:

**Comment by danielfromearth** [comment]
Yep, I can see the "Details" for the build.  Not sure if we want to add this new `lxml_html_clean` package in the pyproject.toml dependencies.  Will be able to look at this more later this afternoon.

**Comment by danielfromearth** [comment]
@mfisher87, with the poetry update reverted, everything checks out. If you approve (again 😄 ), I'll go ahead and merge.

**Review by mfisher87 — APPROVED** [review]

**Review by betolink — APPROVED** [review]
Looks great!

**Pull request merged**
