### PR TITLE
Add utility for getting authentication environment variables

### PR DESCRIPTION
**Pull request by jrbourbeau**
When working with multiple machines, it's often easier to set authentication environment variables than it is to ship a `.netrc` file around. This PR adds a small utility for programmatically retrieving `EARTHDATA_USERNAME` and `EARTHDATA_PASSWORD`

### CODE REVIEW

**Comment by MattF-NSIDC** [comment]
Thinking out loud: I think in this case, the envvar names make sense because Earthdata credentials are likely the same regardless of which application uses them, but I have a habit of namespacing my envvars by prefixing them with an application name, e.g. `EARTHACCESS_EDL_USERNAME` or something.

This is different than the case of an envvar like `PORT` which unequivocally should be `MY_SERVICE_PORT` instead, because many applications need _different_ ports set; I'm not suggesting we do this, just looking for others' thoughts on the interface.

**Review by MattF-NSIDC — APPROVED** [review]
Looks great.

**Comment by betolink** [comment]
Looks neat, how is this different from what `earthaccess.login()` does? the first thing this method does is trying to authenticate with environment variables. If we are using a cluster and we send the `__store__` instance, it's already authenticated no?

**Comment by jrbourbeau** [comment]
> Looks neat, how is this different from what earthaccess.login() does?

This utility is for, after a Python session is already authenticated, easily grabbing environment variables needed to authenticate other machines. For example, if I have a `.netrc` file locally, then `earthaccess.login()` works great. If I then want to provision a bunch of remote machines (that won't have my local `.netrc` file) and call `earthaccess.download()` on them, I'll get authentication errors. Often you can pretty easily set environment variables when provisioning remote machines, so having a little utility for getting the necessary env vars `earthaccess` needs can be useful. 

Here's a specific example of how I'd like to use this with Coiled (though the code being added here isn't Coiled-specific, it could be used by any other library):

```python
import tempfile
import earthaccess
import coiled

# I have a `~/.netrc` file locally on my laptop where this code is running
earthaccess.login()

@coiled.function(
    region="us-west-2",
    environ=earthaccess.auth_environ(),  # This makes sure the remove VMs being spun up here have the right `EARTHDATA_*` variables set 
)
def process(granule):
    with tempfile.TemporaryDirectory() as tmpdir:
        files = earthaccess.download(granule, tmpdir)
        ... # Do things with these files

granules = earthaccess.search_data(...)
results = process.map(granules)
```

> If we are using a cluster and we send the __store__ instance, it's already authenticated no?

That's correct, we just don't do that in all cases (e.g. calling `earthaccess.download` on a list of granules doesn't result in us sending the `__store__` instance)

**Comment by betolink** [comment]
Ooops I merged in the wrong order @jrbourbeau

**Comment by jrbourbeau** [comment]
No worries -- just resolved the merge conflict

**Comment by betolink** [comment]
I think we should merge this one, what do you think @MattF-NSIDC?

**Comment by MattF-NSIDC** [comment]
:rocket:

**Review by mfisher87 — APPROVED** [review]

**Pull request merged**
